#!/bin/sh

set -x

# [10.11.1]
defaults -currentHost write com.apple.systemuiserver dontAutoLoad -array \
  "/Applications/Utilities/Keychain Access.app/Contents/Resources/Keychain.menu" \
  "/System/Library/CoreServices/Menu Extras/Battery.menu" \
  "/System/Library/CoreServices/Menu Extras/Clock.menu" \
  "/System/Library/CoreServices/Menu Extras/TimeMachine.menu" \
  "/System/Library/CoreServices/Menu Extras/Volume.menu"

# [10.11.1]
defaults write com.apple.systemuiserver menuExtras -array \
  "/System/Library/CoreServices/Menu Extras/AirPort.menu" \
  "/System/Library/CoreServices/Menu Extras/Bluetooth.menu" \
  "/System/Library/CoreServices/Menu Extras/TextInput.menu"

# [10.11.1] Show the ~/Library folder
chflags nohidden ~/Library

# [10.9] Disable the sudden motion sensor as it’s not useful for SSDs
# [Probably useless; no way to verify this command works]
sudo pmset -a sms 0

# [10.9] Disable local Time Machine snapshots
sudo tmutil disable
sudo tmutil disablelocal

# [10.9] Disable OSX Dock
defaults write com.apple.dock autohide-delay -float 1000

# [10.9] Disable Dashboard
defaults write com.apple.dashboard mcx-disabled -bool true

# [10.9] Disable Disk verification
defaults write com.apple.frameworks.diskimages skip-verify -bool true
defaults write com.apple.frameworks.diskimages skip-verify-locked -bool true
defaults write com.apple.frameworks.diskimages skip-verify-remote -bool true

# [10.9] Enable full keyboard access for all controls (e.g. enable Tab in modal dialogs)
defaults write NSGlobalDomain AppleKeyboardUIMode -int 3

# Use scroll gesture with the Ctrl (^) modifier key to zoom
defaults write com.apple.universalaccess closeViewScrollWheelToggle -bool true
defaults write com.apple.universalaccess HIDScrollZoomModifierMask -int 262144
defaults write com.apple.universalaccess closeViewZoomFollowsFocus -bool true

# Use Dark mode
defaults write NSGlobalDomain AppleInterfaceStyle -string "Dark"
